### PR TITLE
Newsweek Clone(Milestones 1-6)

### PR DESCRIPTION
**Pull request by SamArsanios**
In this project we:

1. Used HTML and CSS to make a clone of the Newsweek website.
2. Used bootstrap classes to organize the sections in small, medium, and large screens.

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @SamArsanios and @KumarAmitt  ! 👋 👋 👋 

#### You have done well so far :clap: However, there are changes. Kindly work on them and submit them for another code review.

**Recommended**

- [x] Fix your webpage to occupy more of the screen's width like the actual page.

* [x] **Navigation Bar**

- [x] Desktop screens
- It contains the Newsweek logo.

- It contains a date in the same format on the source page.

- It contains Sign in and Subscribe links.

- It contains the main navigation links. 

_**You are missing all the things stated above because you have this style in your page header `d-md-none d-sm-none`**_


**Original**

Screenshot (130)

**Your clone**

Screenshot (131)

- [x] Medium screens

- The elements in the navbar is not properly aligned.

**Original**

Screenshot (132)

**Your clone**

Screenshot (133)

- [x] Small Screens

- [x]  Your navbar is appearing twice and in 2 different formats for some reason. Fix it.

**Original**

Screenshot (135)


**Your clone**

Screenshot (134)

* [x] **Main Content**

- [x] **Featured Stories**
- [x] Desktop-Screens
- There are only 5 stories under this section, your clone, however, has more, please fix this and remove the excesses.

- [x] Small Screens
- In this screen size, the Featured Stories section comes right after the Top Story.

- [x] **Top Story**
 - [x] Desktop-Screens
 - Adjust the width of the first 3 sections(The Featured Stories, Top Story and Debate) to look the same as the Newsweek page.

 - Reduce the font size used for the article title from `24px` to `22px`.

- [x] **Opinion**

- [x] Desktop-Screens
- You are missing the "Free Sign Up" form after the Opinions section.

- [x] Small-Screens 
-  On small screens, the opinions section should come after the Debate and before More stories.

- [x] **More Stories**
- [x] Desktop-Screens
- You are missing the lines in this section. Use `hr` to add it.

- [x] Small Screens
-  It should come after the Opinions Section and before "My Turn" section.

- [x] **In The Magazine**
- [x] Desktop-Screens
- The first article image should have a bigger image, please fix it.
- You have a margin between the "See All features" and the image card, please remove it.
- You are missing the text in the red background in this section.

**Original**

Screenshot (137)

**Your clone**

Screenshot (136)

- [x] **Featured  Slideshows**

- [ ]Small Screens
- In this screen size, all articles should be full width, with the 2 big images occupying full width, and the smaller images and article titles being 50% each in width.

- [x] **Subscribe and Nesletter section**

- [x] Desktop-Screens
- Fix this section to look as similar as possible to the actual site's. Use [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) tool to determine the font-family used as well.

**Original**

Screenshot (139)

**Your clone**

Screenshot (138)

- [x] Medium and Small screens
- The Newsletter and Subscribe sub-section should be a single column and full width.

- [x] **Footer**
- [x] Desktop-Screens

- Your footer needs more work, especially the logo used here.

**Original**

Screenshot (140)

**Your clone**

Screenshot (141)

- [x] Small Screens

- The footer wraps up to one column.

**Original**

Screenshot (143)

**Your clone**

Screenshot (142)



_**I understand that the changes are quite a lot, but take it as a learning process and as time goes by, you'll look back at this "stumbling block" in the path of your progress as a stepping stone!**_
__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @SamArsanios  & @KumarAmitt**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] for the Newsweek logo it has to be an image logo not text.

- [x] to make the page responsive like the original one, please put everything including the navbar and footer in one big container and add the container and p-0 bootstrap classes to it.

- [x] also you should only use bootstrap  for responsiveness. that means you have to remove every margin/padding from the CSS unless you absolutely need it.

- [x] I see you are using a lot of CSS for styling, this should be the case. please make sure to use only bootstrap for styling unless you need it for colors.

- [x] in  the navbar on the mobile view the login link is replaced with a user icon 

Capture




### Optional 🟢 

 

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUIRED 🔴 ♻️ 

Hello team @SamArsanios and @KumarAmitt  👋 👋 
✔️ Good job on working on the comments left by the TSE's
✔️ Your project looks good already

Before we mark it as complete, check out the comments below ⬇️ 

- [x]  On the tablet view, you are missing the `Login ` text, kindly add it.

Originial| Clone
------------ | -------------
image | image

Notice the difference? 


- [x]  On the mobile view, the `Login` text, changes to a user icon. Kindly add it

Original | Clone
------------ | -------------
image | image

- [x] On the mobile menu, the featured stories should appear right below the top story. This is followed by the debate section, more stories at last my turn, and the culture and travel section. Check on this 😄 . You can refer to this [link](https://www.newsweek.com/).

- [x] Change the image on the newsletter section to resemble the original page. You can refer to this [link](https://www.newsweek.com/).

Original | Clone
------------ | -------------
image| image

- [x]  On the mobile menu, define the width and height of the images on the subscribe section. 

Original | Clone
------------ | -------------
image| image

That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
Feel free to reach out on slack if you have any questions

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @SamArsanios & @KumarAmitt**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] for the Newsweek logo it has to be an image logo not text.

- [ ] Change the image on the newsletter section to resemble the original page.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @KumarAmitt  & @SamArsanios**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
